<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Surefire test"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="29,006">
    <properties></properties>

            <testcase
                name="addProductsToWishlist"
                time="11,317"
                classname="WishListTest">

            <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
                <![CDATA[java.lang.AssertionError: expected [3] but found [4]
                org.testng.Assert.fail(Assert.java:110)org.testng.Assert.failNotEquals(Assert.java:1413)org.testng.Assert.assertEqualsImpl(Assert.java:149)org.testng.Assert.assertEquals(Assert.java:131)org.testng.Assert.assertEquals(Assert.java:655)org.testng.Assert.assertEquals(Assert.java:665)WishListTest.addProductsToWishlist(WishListTest.java:32)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)java.base/java.lang.reflect.Method.invoke(Method.java:577)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:806)org.testng.TestRunner.run(TestRunner.java:601)org.testng.SuiteRunner.runTest(SuiteRunner.java:433)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)org.testng.SuiteRunner.run(SuiteRunner.java:330)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)org.testng.TestNG.runSuitesLocally(TestNG.java:1176)org.testng.TestNG.runSuites(TestNG.java:1099)org.testng.TestNG.run(TestNG.java:1067)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </failure>
    </testcase>


            <testcase
                name="goToWishlist"
                time="6,177"
                classname="WishListTest">
            </testcase>
            <testcase
                name="shoppingButtonInWishList"
                time="11,512"
                classname="WishListTest">
            </testcase>
</testsuite>
