<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J7FNVMD" failures="1" tests="6" name="Surefire test" time="68.124" errors="0" timestamp="2022-10-07T17:39:23 EEST">
  <testcase classname="FooterTest" name="goToBuyersHelpLink" time="1.468"/>
  <testcase classname="FooterTest" name="goToSellersHelpLink" time="1.097"/>
  <testcase classname="FooterTest" name="goToTariffsLink" time="2.499"/>
  <testcase classname="WishListTest" name="addProductsToWishlist" time="11.317">
    <failure type="java.lang.AssertionError" message="expected [3] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [4]
at WishListTest.addProductsToWishlist(WishListTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- addProductsToWishlist -->
  <testcase classname="WishListTest" name="goToWishlist" time="6.177"/>
  <testcase classname="WishListTest" name="shoppingButtonInWishList" time="11.512"/>
</testsuite> <!-- Surefire test -->
